name = "spin-mama-bonus-ch"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=spin-mama-bonus.ch"
HMAC_KEY = "ecad40dfd55b766c4575924799757e0507de46a7099fee289124e577c655f8a6"
COOKIE_NAME = "15j"
PLAY_PATH = "discover"
BUTTON_ID = "p3d821ceb0da742e3e3f59f25611bd031"
GATE_SALT = "602d8fb02164d5f5"
